# Generated by Django 2.2.5 on 2019-09-05 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0002_remove_professor_formacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
